### ISSUE TITLE
wasm source?

### ISSUE THREAD

**Issue by scratchyone** [Zeyu-Li/lua-runner#2]
Hi! This repo contains a compiled WASM binary. Are you willing to share the code that was used to produce that compiled binary? I'd love to make some modifications to adapt some stuff for my specific needs but that's not possible without the original source. Thank you!

**Comment by Zeyu-Li** [comment]
@scratchyone sorry about the late response :p I don't know how I didn't see this, but here it is if u still need it: https://github.com/Zeyu-Li/Lua-Online... it's based on this fork https://github.com/Dreagonmon/wasm_lua
